### ISSUE TITLE
Bedrust unable to get credentials from an external process natively from the SDK

### ISSUE THREAD

**Issue by schniber** [darko-mesaros/bedrust#28]
Hello,

First of all Kudos to you on bringing this to life ! it really is a great asset to bring more GenAI stuff closer to the dev as part of next gen dev experiences !

While trying to play around with Bedrust, I was unable to get it to work when my environment sources credentials with an external process as per https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

Bedrust error message states that the credentials provider was not enabled as you can see in the attached screenshot:

![image (22)](https://github.com/darko-mesaros/bedrust/assets/75125134/35b1cc9f-e6b7-4be5-a7b7-eb98108707a7)

Here's an example content of `~/.aws/config`:

```sh
[profile developer]
credential_process = /opt/bin/awscreds-custom --username helen
```

Thanks a lot !

Bests and keep it up

**Comment by darko-mesaros** [comment]
@schniber - I believe this issue is now fixed. Please do try :)

**Comment by schniber** [comment]
Hey @darko-mesaros !
Good job looks like all is good now ! Keep it up mate !
